### ISSUE TITLE
Feature Request: Get / Set schedule

### ISSUE THREAD

**Issue by steelixb** [gndean/home-assistant-hypervolt-charger#24]
It would be super useful if we could get and set the schedule. I don't understand the limitation that prevents this right now, as I have various other integrations that allow me to get and set dates and times. As an example, I change the scheduled charging of my house battery through a service, passing a JSON payload:

```yaml
service: givenergy_local.enable_timed_charge
data: >
  {% set startTime = now() %}
  {% set endTime = as_datetime(states('sensor.octopus_intelligent_offpeak_end')).astimezone() %}
  {
    "start_time": "{{ '%02d' % startTime.hour }}:00:00",
    "end_time": "{{ '%02d' % endTime.hour }}:{{ '%02d' % endTime.minute }}:00",
    "device_id": "xxxx"
  }
```

This would be useful for charging one of our cars that doesn't support Intelligent Octopus or specifying a target battery SoC, as we could automate scheduling to always charge to 80%
